version: '3.6'
services:
  web:
    image: "php:8.1-apache"
    volumes:
      - /www:/var/www/html
    ports:
      - 8001:80
  composer:
    image: "composer:latest"
    working_dir:
      - /www:/var/www/html
    command: update
  mysql:
    image: "mysql:latest"
    restarts: always
    ports: '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123
